-- Schema creation script for Banking System
-- Compatible with both H2 and PostgreSQL

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'CLIENT',
    email VARCHAR(255),
    first_name VARCHAR(100),
    last_name VARCHAR(100)
);

-- Add missing columns to existing users table (for databases created before this migration)
ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS first_name VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_name VARCHAR(100);

CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    customer_type VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR(24) NOT NULL UNIQUE,
    balance NUMERIC(19,2) NOT NULL DEFAULT 0.00,
    account_type VARCHAR(20) NOT NULL,
    customer_id BIGINT NOT NULL REFERENCES customers(id)
);

-- Migration: Add customer_id column to existing accounts table (for databases created before this migration)
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS customer_id BIGINT;

-- Migration: Drop old user_id column (replaced by customer_id) for databases created before this migration
ALTER TABLE accounts DROP COLUMN IF EXISTS user_id;

CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20) NOT NULL,
    amount NUMERIC(19,2) NOT NULL,
    source_account_number VARCHAR(24),
    destination_account_number VARCHAR(24),
    balance_after NUMERIC(19,2),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    account_id BIGINT NOT NULL REFERENCES accounts(id)
);

-- Migration: Add balance_after column to existing transactions table (for databases created before this migration)
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS balance_after NUMERIC(19,2);

CREATE INDEX IF NOT EXISTS idx_transactions_account_id ON transactions(account_id);
CREATE INDEX IF NOT EXISTS idx_transactions_created_at ON transactions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_accounts_customer_id ON accounts(customer_id);